#ifndef FLB_ARCHIVER_VERSION_H
#define FLB_ARCHIVER_VERSION_H

#define FLB_VERSION_MAJOR "1"
#define FLB_VERSION_MINOR "0"
#define FLB_VERSION_PATCH "0"

#define FLB_VERSION FLB_VERSION_MAJOR "." FLB_VERSION_MINOR "." FLB_VERSION_PATCH

#endif  // FLB_ARCHIVER_VERSION_H
